In [1]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"yazhini4225","key":"1a6ba5ceade148cb5a7831e69292e05b"}'}

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("drgfreeman/rockpaperscissors")

print("Path to dataset files:", path)

Path to dataset files: /kaggle/input/rockpaperscissors


In [3]:
pip install opencv-python scikit-learn tensorflow matplotlib

In [4]:
DATASET_PATH = "rockpaperscissors"

In [5]:
import kagglehub
import os
import cv2
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
subfolders = os.listdir(path)
if "rockpaperscissors" in subfolders:
    DATASET_PATH = os.path.join(path, "rockpaperscissors")
elif "rps-cv-images" in subfolders:
    DATASET_PATH = os.path.join(path, "rps-cv-images")
else:
    raise Exception("Could not find rock/paper/scissors folder in dataset.")

print("Using dataset folder:", DATASET_PATH)

Using dataset folder: /kaggle/input/rockpaperscissors/rps-cv-images


In [6]:
IMG_SIZE=64

In [9]:
X = []
y = []

for label, folder in enumerate(["rock", "paper", "scissors"]):
    folder_path = os.path.join(DATASET_PATH, folder)
    for file in os.listdir(folder_path):
        img_path = os.path.join(folder_path, file)
        img = cv2.imread(img_path)
        if img is not None:
            img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
            X.append(img.flatten())  # Flatten to 1D for KNN
            y.append(label)

X = np.array(X)
y = np.array(y)

print(f"Loaded {len(X)} images.")

Loaded 2188 images.


In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

print("Raw Pixel KNN Accuracy:", accuracy_score(y_test, y_pred))


Raw Pixel KNN Accuracy: 0.95662100456621


In [11]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

Confusion Matrix:
 [[150   1   0]
 [  3 124   1]
 [  8   6 145]]


In [12]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred, target_names=["rock", "paper", "scissors"]))

              precision    recall  f1-score   support

        rock       0.93      0.99      0.96       151
       paper       0.95      0.97      0.96       128
    scissors       0.99      0.91      0.95       159

    accuracy                           0.96       438
   macro avg       0.96      0.96      0.96       438
weighted avg       0.96      0.96      0.96       438



In [13]:
from sklearn.metrics import f1_score

print("Average F1 Score:", f1_score(y_test, y_pred, average="weighted"))

Average F1 Score: 0.9564756669517506
